version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: reacttemplate_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: ReactTemplateDb_Dev
      MYSQL_USER: reactapi
      MYSQL_PASSWORD: Welcome1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./Scripts/setup_mysql.sql:/docker-entrypoint-initdb.d/setup.sql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  mysql_data: